[Feature] Add FloatingView of nmap & Changing marker(pin)
JamongSoda/IntoHistory pull request #106
Opened 2022-08-16 10:18 UTC by JUNY0110

## Key Changes 🔥 (주요 구현/변경 사항)
 - 마커(핀) 터치 시 장소 및 주소 설명하는 플로팅 뷰 추가
 - 마커 선택 시 '선택한 것'과 '선택하지 않은' 마커(핀)을 전환하는 기능 추가

## ToDo 📆 (남은 작업)
- [ ] 지도 상단 아이콘 클릭 시 뒤로가기 네비게이션 기능
- [ ] 상세코스 리스트 데이터 연동

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
 - ㅠㅠ

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #91.

2022-08-16 10:27 UTC, taek0622 requested changes
고생하셨습니다.
맵 API 관련한 내용이 복잡한 로직이 많았는데, 정말 열심히 해주셔서 감사해요~
몇몇 고쳐야할 부분 리뷰했습니다. 항상 감사해요 에디~👍

2022-08-16 10:27 UTC, taek0622 commented on IntoHistory/CourseListView/CourseListViewController.swift
> +import SwiftUI
p2;
사용되지 않는 프레임워크 `SwiftUI`가 import 된 것 같습니다.
삭제 부탁드려요~

2022-08-16 10:27 UTC, taek0622 commented on IntoHistory/NMapViewController.swift
> +        addressLabel.text = courseJSONLoader[1].course_pins[0].pin_title
p4;
후에 코어데이터로 변경되어야 할 내용입니다.

2022-08-16 10:27 UTC, taek0622 commented on IntoHistory/NMapViewController.swift
> +                addressLabel.text = courseJSONLoader[1].course_pins[pinNum].pin_title
p4;
마찬가지로 후에 코어데이터로 내용이 바뀌어야할 것 같습니다.

2022-08-16 12:26 UTC, deslog reviewed
빌드하고 나서 Thread 에러가 발생하는데 확인부탁드려도 될까요? ㅠㅠ

```Thread 1: EXC_BAD_ACCESS (code=1, address=0x24afffff0)```

2022-08-16 12:27 UTC, taek0622 commented
> 빌드하고 나서 Thread 에러가 발생하는데 확인부탁드려도 될까요? ㅠㅠ
> 
> `Thread 1: EXC_BAD_ACCESS (code=1, address=0x24afffff0)`

아마 해당 에러는 맵 부분에서 발생할 것으로 보입니다.
맵 부분은 시뮬레이터가 아니라 실제 디바이스에서 테스트해야만 합니다 ㅠㅠ

2022-08-16 12:27 UTC, deslog commented
> 빌드하고 나서 Thread 에러가 발생하는데 확인부탁드려도 될까요? ㅠㅠ
> 
> `Thread 1: EXC_BAD_ACCESS (code=1, address=0x24afffff0)`

엥 아님니다 꺼켯하니까 잘되네요 ^___^ 죄송합니다 후후

2022-08-16 12:35 UTC, deslog reviewed
고생하셨습니다! p1,. p2 수정해주시면 감사하겟씁니다!

2022-08-16 12:35 UTC, deslog commented on IntoHistory/NMapViewController.swift
> +    let hStackView: UIStackView = {
p1;

접근제어자 추가 부탁드립니다!
```suggestion
    private let hStackView: UIStackView = {
```

2022-08-16 12:35 UTC, deslog commented on IntoHistory/NMapViewController.swift
> +    let vStackView: UIStackView = {
p1;

접근제어자 추가 부탁드려요! 아래 let들도 전부 필요해보이지만, 리뷰는 여기까지만 달겠습니다. 수정 부탁드려요! 👍
```suggestion
    private let vStackView: UIStackView = {
```

2022-08-16 12:35 UTC, deslog commented on IntoHistory/NMapViewController.swift
> +        hStackView.uiViewShadow(backgroundView: hStackView)
p2;

여기 레이아웃 주는 func은 ```viewDidLoad```에서 해주신 이유가 있을까요?
저희 viewcontroller에서는 
```swift
func layout() { } 
```
을 이용하기로 했었어서 변경해주시면 감사할 것 같습니다!

2022-08-17 02:22 UTC, JUNY0110 commented on IntoHistory/NMapViewController.swift
> +        hStackView.uiViewShadow(backgroundView: hStackView)
> p2;
> 
> 여기 레이아웃 주는 func은 `viewDidLoad`에서 해주신 이유가 있을까요? 저희 viewcontroller에서는
> 
> ```swift
> func layout() { } 
> ```
> 
> 을 이용하기로 했었어서 변경해주시면 감사할 것 같습니다!

naverMapView라는 변수의 NMFNaverMapView(frame: view.frame)에서 view를 사용하기 위해 viewDidLoad에 있어야하며, naverMapView변수를 func layout()으로 빼면, naverMapView변수를 func에서 받지 못하는 문제가 있어 부득이하게 위와 같이 했습니다.

2022-08-17 02:25 UTC, JUNY0110 commented on IntoHistory/CourseListView/CourseListViewController.swift
> +import SwiftUI
> p2;
> 사용되지 않는 프레임워크 `SwiftUI`가 import 된 것 같습니다.
> 삭제 부탁드려요~

0f01a68 수정하였습니다.

2022-08-17 02:25 UTC, JUNY0110 commented on IntoHistory/NMapViewController.swift
> +    let hStackView: UIStackView = {
> p1;
> 
> 접근제어자 추가 부탁드립니다!

6c480ff
수정하였습니다.

2022-08-17 02:26 UTC, JUNY0110 commented on IntoHistory/NMapViewController.swift
> +    let vStackView: UIStackView = {
> p1;
> 
> 접근제어자 추가 부탁드려요! 아래 let들도 전부 필요해보이지만, 리뷰는 여기까지만 달겠습니다. 수정 부탁드려요! 👍

6c480ff
수정하였습니다.

2022-08-17 04:30 UTC, deslog commented on IntoHistory/NMapViewController.swift
> +        hStackView.uiViewShadow(backgroundView: hStackView)
오호 그렇군요?!? 알려주셔서 감사합니다!

2022-08-17 04:30 UTC, deslog approved these changes
굿굿굿!!!!!

2022-08-17 04:55 UTC, taek0622 approved these changes
고생하셨습니다.
Approve를 한 줄 알았더니 변경하지 않았었군요..
늦은 확인 죄송합니다.
항상 감사해요 에디~

2022-08-17 04:55 UTC, merged