[Feature] Notification 기능구현
JamongSoda/IntoHistory pull request #114
Opened 2022-08-16 19:19 UTC by deslog

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- pin 위치기반 Notification 구현

## Key Changes 🔥 (주요 구현/변경 사항)

## ToDo 📆 (남은 작업)
- [ ] 코스를 다 돌면 AR 팝업 띄우기
- [ ] AR 팝업 선택 시 메인뷰컨으로 이동

## ScreenShot 📷 (참고 사진)
<img width="394" alt="image" src="https://user-images.githubusercontent.com/103012104/184925235-dabec780-6c28-4dbb-ae9a-dd5638e13efb.png">

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #54

2022-08-16 19:20 UTC, GODNOEL approved these changes
가보자~

2022-08-17 01:22 UTC, taek0622 requested changes
고생하셨습니다.
일부 수정사항 리뷰 남겼습니다. 확인 부탁드려요~

2022-08-17 01:22 UTC, taek0622 commented on IntoHistory/AppDelegate.swift
> +
p3;
불필요하게 공백이 너무 많이 들어간 것 같네요.

2022-08-17 01:22 UTC, taek0622 commented on IntoHistory/AppDelegate.swift
>          // Override point for customization after application launch.
p3;
이런 주석들이 많이 남아있던데, 혹시 꼭 필요한 주석일까요?
그렇지 않다면 삭제해주시면 좋을 것 같습니다.

2022-08-17 01:22 UTC, taek0622 commented on IntoHistory/AppDelegate.swift
> +
p2;
내부 내용이 미구현된 함수인데, 꼭 필요하지 않다면 삭제하는 것이 좋을 것 같습니다.

2022-08-17 01:22 UTC, taek0622 commented on IntoHistory/LocationService.swift
> +    let courseData = LoadingCourseJSON().courses.map{$0.course_pins}
p2;
데이터 내용을 코어데이터에서 가져오는 쪽으로 변경해야할 것 같습니다.
현재 json은 오직 앱 최초 실행 때 한번만 코어데이터에 내용을 저장하는 곳에만 사용됩니다.

2022-08-17 01:22 UTC, taek0622 commented on IntoHistory/LocationService.swift
> +               .sorted{ tuple1, tuple2 in return tuple1.1 < tuple2.1 }
p2;
tuple1, tuple2 라는 네이밍은 직관성을 떨어뜨릴 것 같습니다.

2022-08-17 01:22 UTC, taek0622 commented on IntoHistory/LocationService.swift
> +      }
p5;
현재 새 PR에서 코어데이터 매니저가 추가되었습니다.
후에 거기서 따오는 쪽으로 변경되면 좋을 것 같습니다.

2022-08-17 01:22 UTC, taek0622 commented on IntoHistory/LocationService.swift
> +            let long = arr[i].1
p2;
아마도 tuple들을 모아놓은 배열에서 0번째 요소와 1번째 요소를 lat, lng으로 가져오는 내용 같은데 튜플 내용을 가져올 때 꼭 0, 1을 사용해야만 가져올 수 있을까요?
약간 직관성이 떨어지는 것 같습니다.
튜플의 요소에도 이름을 줄 수 있는데 해당 방법을 사용해 보는 건 어떨까요?
아래에 레퍼런스 첨부합니다.

[ZeddiOS - Swift) tuple](https://zeddios.tistory.com/238)

2022-08-17 01:22 UTC, taek0622 commented on IntoHistory/LocationService.swift
> +//        }
p2;
불필요한 주석 삭제 부탁드립니다~

2022-08-17 02:35 UTC, JUNY0110 requested changes
고생하셨습니다!

2022-08-17 02:35 UTC, JUNY0110 commented on IntoHistory/Info.plist
> +	<string>위치접근 항상허용</string>
p4.
사용자에게 왜 위치접근 권한을 사용해야하는지에 대해 자세한 설명을 해야 리젝사유를 면할 수 있기 때문에 디테일한 설명이 필요합니다.
'사용자의 위치에 따른 전쟁영웅 및 독립운동가에 관한 알림을 받기 위해 위치정보에 대한 권한이 필요합니다'와 같은 문구가 적절할 것 같습니다.

2022-08-17 02:35 UTC, JUNY0110 commented on IntoHistory/LocationService.swift
> +                        // error
p2.
불필요 주석입니다~

2022-08-17 04:31 UTC, deslog commented on IntoHistory/AppDelegate.swift
> +
앱딜리게이트 기본함수인것같은데 미뉴 말처럼 사용되지 않는 부분이라 전부 삭제했습니다! 추가로 앱딜리게이트에 있는 필요없는 주석과 공백을 전부 정리했습니다~
[379f690](https://github.com/JamongSoda/IntoHistory/pull/114/commits/379f690e66fecc66b740b3781ae9f2668b41e227)

2022-08-17 04:32 UTC, deslog commented on IntoHistory/AppDelegate.swift
>          // Override point for customization after application launch.
네! 잘못들어가있네요 ㅠㅠ 감사합니다! 

[379f690](https://github.com/JamongSoda/IntoHistory/pull/114/commits/379f690e66fecc66b740b3781ae9f2668b41e227)

2022-08-17 04:32 UTC, deslog commented on IntoHistory/AppDelegate.swift
> +
넵 수정완료! [379f690](https://github.com/JamongSoda/IntoHistory/pull/114/commits/379f690e66fecc66b740b3781ae9f2668b41e227)

2022-08-17 04:33 UTC, deslog commented on IntoHistory/LocationService.swift
> +      }
네~ ! 머지되면 변경하겠습니다!

2022-08-17 04:40 UTC, deslog commented on IntoHistory/LocationService.swift
> +            let long = arr[i].1
오? 몰랐던 정보인데 감사합니다. 좋은 방법이네요!!! [39efc92](https://github.com/JamongSoda/IntoHistory/pull/114/commits/39efc92587703c9fe2d6e310b3feb9a762a7cde4)

2022-08-17 04:43 UTC, deslog commented on IntoHistory/LocationService.swift
> +                        // error
수정했습니다! [7095284](https://github.com/JamongSoda/IntoHistory/pull/114/commits/7095284680aa614e0bdf1623d206bd85ea0aafe5)

2022-08-17 04:43 UTC, deslog commented on IntoHistory/LocationService.swift
> +//        }
[7095284](https://github.com/JamongSoda/IntoHistory/pull/114/commits/7095284680aa614e0bdf1623d206bd85ea0aafe5)
수정완료!

2022-08-17 04:46 UTC, deslog commented on IntoHistory/Info.plist
> +	<string>위치접근 항상허용</string>
네 [26c18ee](https://github.com/JamongSoda/IntoHistory/pull/114/commits/26c18ee36435d571d813b0ef7bf08be3d7dfc86f)
일단 에디가 써주신대로 수정하였습니당

2022-08-17 04:48 UTC, deslog commented on IntoHistory/LocationService.swift
> +    let courseData = LoadingCourseJSON().courses.map{$0.course_pins}
네!! 혹시 이부분 코어데이터 매니저 머지되고 수정해도 될까요?! 매니저 합쳐지면 어차피 다시 봐야할것 같아서요!

2022-08-17 04:51 UTC, taek0622 commented on IntoHistory/LocationService.swift
> +    let courseData = LoadingCourseJSON().courses.map{$0.course_pins}
넵넵 좋습니다.

2022-08-17 05:09 UTC, deslog commented on IntoHistory/LocationService.swift
> +               .sorted{ tuple1, tuple2 in return tuple1.1 < tuple2.1 }
넵 수정완료했습니다!
[8c3651f](https://github.com/JamongSoda/IntoHistory/pull/114/commits/8c3651fcfd0a66ff0362547782bbf970d9eb26f2)

```.1```로 되어있는것도 아까 알려주신 tuple naming지정해서 바꾸려고 했는데, CLLRegion의 특수한 형태가 tuple자체로 이루어져있어서 이부분은 어떻게 바꾸어야할지 모르겠어서 일단 놔뒀습니다 ㅠㅠ

2022-08-17 07:45 UTC, taek0622 approved these changes

2022-08-17 07:46 UTC, JUNY0110 approved these changes

2022-08-17 07:46 UTC, merged