Main view board
JamongSoda/IntoHistory pull request #116
Opened 2022-08-16 19:29 UTC by deslog

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- main View칠판에 컨텐츠를 띄웁니다.

## Key Changes 🔥 (주요 구현/변경 사항)
- 날짜를 받아서 오늘 날짜가 공휴일인경우, 그에 맞는 content를 띄워줍니다.
- 일단 공휴일이 아닐 경우, random하게 배열에서 값을 추출해서 넣게 해두었습니다. 고정값으로 갈지, random 배열에 데이터를 추가해서 넣을지 고민중입니다.. (공수가 적은걸로,,,)
- notification이 뜨면 AR view로 이동해달라는 문구?를 띄워줘야하는데 아직 notification 이 develop 에 머지가 안되어 다음작업으로 넘기겠습니다. (이슈파고 새로 만들게요)
- 글꼴 추가했습니다.

## ToDo 📆 (남은 작업)
- [ ] notification 관련 칠판에 띄우기

## ScreenShot 📷 (참고 사진)

![simulator_screenshot_4982640C-83B8-4742-84F8-A8CCD3D7E98F](https://user-images.githubusercontent.com/96969693/184964787-fe8cf654-061c-4081-826a-20b289efd52a.png)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 해당 pr은 type branch를 develop으로 보내는 pr입니다. 빠른 머지를 위해 type branch로의 머지는 한 명만 approve 했을때 그냥 머지해버렷습니다! 해당 pr만 주의깊게 잘 봐주세용 

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #110

2022-08-16 19:32 UTC, GODNOEL approved these changes
가~~~즈~~~~아~~~!!!

2022-08-17 01:30 UTC, taek0622 requested changes
고생하셨습니다.
일부 수정이 필요한 부분에 리뷰 남겼습니다. 확인 부탁드려요~

2022-08-17 01:30 UTC, taek0622 commented on IntoHistory/Extension/Date+Extension.swift
> +        dateFormatter.timeZone = TimeZone(identifier: "UTC")
p2;
저희 앱 사용 국가가 한국인 만큼 timezone이 utc가 아닌 KST가 되어야할 것 같습니다. 아래에 KST 변환 관련 레퍼런스 첨부합니다.

[Eddie Kwon  - Development log for ML, iOS - Date를 UTC 와 KST로 출력하기 - swift](https://eddiekwon.github.io/swift/2018/11/27/UTCtoKST/)

2022-08-17 01:30 UTC, taek0622 commented on IntoHistory/MainView/MainViewController.swift
> +        $0.text = ""
P2;
빈 텍스트를 준다면 해당 부분은 삭제되어도 같은 동작을 할 것으로 보입니다.

2022-08-17 01:30 UTC, taek0622 commented on IntoHistory/MainView/MainViewController.swift
> +        // 공휴일에있으면= 특정문구, 평소 = 역사정보, notification = noti 내용
p2;
설명 주석은 개발할 때 편하지만, 이미 완성된 함수라면 불필요한 주석이므로 삭제 부탁드립니다.

2022-08-17 02:38 UTC, JUNY0110 approved these changes
고생하셨습니다

2022-08-17 02:38 UTC, JUNY0110 commented on IntoHistory/MainView/BlackBoardTextData.swift
> +    case sunkook = "1117"    // 순국선열의날
굿! 잘 추가해주신 것 같습니다

2022-08-17 04:15 UTC, deslog commented on IntoHistory/Extension/Date+Extension.swift
> +        dateFormatter.timeZone = TimeZone(identifier: "UTC")
아니ㅋㅋㅋㅋㅋㅋㅋㅋㅋ이게뭐람 집중안되던걸 이렇게 티내내요,,, 날카로운 캐치  감사합니다!!! [46c4d3d](https://github.com/JamongSoda/IntoHistory/pull/116/commits/46c4d3de68b5786a0977aae2c5aef6a06e867a0f)

2022-08-17 04:16 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +        $0.text = ""
제가 이전에 프로젝트할때, text에 초기값을 주지않아서 가끔 text출력이 딜레이되는 현상(앱이 실행되면 0.몇초 늦게 uilabel이 생성됨)이 생겼었는데, 지금은 정상적으로 동작하여도 문제가 될것 같아서 초기값으루 빈 string을 넣어두었습니다. 혹시 그냥 빈string값으로 두면 크게 문제가 생길까요?!

2022-08-17 04:18 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +        // 공휴일에있으면= 특정문구, 평소 = 역사정보, notification = noti 내용
웁스 감사합니다! [5cb276c](https://github.com/JamongSoda/IntoHistory/pull/116/commits/5cb276cabd548e9017b49d9f6623f7ad3e602629)

2022-08-17 04:22 UTC, taek0622 commented on IntoHistory/MainView/MainViewController.swift
> +        $0.text = ""
아하, 그렇다면 남겨두어도 좋습니다만, "테스트"말고 다른 문구로 대체는 어떨까요?

2022-08-17 04:23 UTC, taek0622 approved these changes
고생하셨습니다~

2022-08-17 04:29 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +        $0.text = ""
오오 네 지금 ```""``` 이렇게 빈 string으로 들어가있어요!

2022-08-17 05:13 UTC, merged