[Design] Mainview Layout 구현 및 관련 리소스 추가
JamongSoda/IntoHistory pull request #53
Opened 2022-08-12 12:28 UTC by GODNOEL

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 메인뷰 레이아웃 코드 추가 
<br/>
## Key Changes 🔥 (주요 구현/변경 사항)
- 메인뷰의 레이아웃을 구현했습니다.  
<br/>
## ToDo 📆 (남은 작업)
- [ ] 데이터가 생기면 칠판의 라벨에 불러오는 작업
- [ ] 칠판의 커스텀 폰트 적용하는 작업

## ScreenShot 📷 (참고 사진)
<img width="768" alt="image" src="https://user-images.githubusercontent.com/103012104/184352022-4e8821b4-a485-4877-ad6e-f6de1ff37fb6.png">

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 코드에서 이상하거나 개선할 점 있으시면 말씀 부탁드립니다.
- 스크롤뷰에서 하단이 너무 길어지거나 짧아지는 현상이 발생하는데 알림을 구현하면서 수정하도록 하겠습니다
<br/>
## Reference 🔗
- 없음
## Close Issues 🔒 (닫을 Issue)
Close #25

2022-08-12 12:39 UTC, taek0622 approved these changes
고생하셨습니다~
디자인에 개발까지 진짜 바쁠텐데 너무 잘 해주셔서 감사합니다~

2022-08-12 12:39 UTC, taek0622 commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +        render()
p3;
render라는 이름도 충분히 직관적이지만, 조금 더 알아보기 좋은 이름을 같이 상의해봐도 좋을 것 같습니다.

2022-08-12 12:39 UTC, taek0622 commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +        ])
질문;
여기에는 `anchor()`를 사용하지 않은 특별한 이유가 있을까요?

2022-08-12 12:39 UTC, taek0622 commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +        labelStack.anchor(left: buttonBackground.leftAnchor, paddingLeft: 25)
p5;
현재 컨벤션에는 없지만, `anchor()` 사용시 가독성을 위해 파라미터마다 라인을 나눠보는 것이 어떨지 제안해봅니다.

2022-08-12 12:39 UTC, taek0622 commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +    }()
p5;
반영하지 않아도 되는 사항입니다만, ui를 정의할 때, 현재 사용하신 방식과 같이 정의할지, 혹은 아래와 같이 정의할지 논의가 필요할 것 같습니다.
해당 부분은 내일 스크럼을 마친 후 이야기 나누면 좋을 것 같습니다.
```swift
private let buttonBackground: UIView = {
    $0.translatesAutoresizingMaskIntoConstraints = false
    $0.backgroundColor = UIColor.white
    $0.layer.cornerRadius = 10
    return $0
}(UIView())
```

2022-08-12 12:39 UTC, taek0622 commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +    private let buttonBackground: UIView = {
질문;
버튼을 정의할 때, UIButton이라는 요소가 있는 것으로 아는데, UIView로 정의해주신 특별한 이유가 있는지 궁금합니다.

2022-08-12 13:05 UTC, GODNOEL commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +        render()
넵 내일 스크럼에서 말해보아요

2022-08-12 13:08 UTC, GODNOEL commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +        ])
제가 코드를 잘못 이해한건지 anchor()를 사용하니까 오류가 나서 기본 오토레이아웃을 사용했습니다.ㅠㅠ
anchor()를 응용해서 가능한지 한번 더 시도해 보겠습니다.

2022-08-12 13:09 UTC, GODNOEL commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +        labelStack.anchor(left: buttonBackground.leftAnchor, paddingLeft: 25)
넵 내일 스크럼때 모두와 한번 상의하고 정하면 좋을것같습니다!

2022-08-12 13:10 UTC, GODNOEL commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +    }()
오 저런 코드를 많이 봤는데 저도 좋은것같아요!
내일 스크럼 때 논의해보아요

2022-08-12 13:12 UTC, GODNOEL commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +    private let buttonBackground: UIView = {
처음에 UIButton.Configuration 이용해 코드를 작성했는데 
해당 요소가 IOS 15부터 지원하고 텍스트 라벨 길이에 따라 이미지 뷰의 위치가 일정하지않아
UIView로 제작후에 해당 뷰에 제스처를 주는 방향으로 작업했습니다.

2022-08-12 13:26 UTC, taek0622 commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +    private let buttonBackground: UIView = {
우선, 저희 프로젝트 최소 지원사양이 iOS 15이기 때문에 `UIButton.configuration`을 사용해도 괜찮을 것 같습니다.
또한, `UIButton.configuration`이 아니더라도 커스텀 버튼을 구현하는 방법이 있어서 아래에 레퍼런스 첨부합니다.

[[iOS] 커스텀 버튼 구현하기(스토리보드형, 코드형) - HoonIOS](https://boidevelop.tistory.com/105)

2022-08-12 13:36 UTC, taek0622 requested changes
약간의 리뷰를 추가했습니다.
한 번에 확인 못하고 추가해서 죄송합니다.

2022-08-12 13:36 UTC, taek0622 commented on IntoHistory/MainView/MainViewController.swift
> +    private func setbuttonGesture() {
p2;
`setbuttonGesture`라는 이름은 함수 이름 규칙 `camelCase(lowerCamelCase)` 규칙에 맞지 않는 것 같습니다.
`setButtonGesture`로 바꾸면 좋을 것 같아요~

2022-08-12 13:36 UTC, taek0622 commented on IntoHistory/MainView/MainViewController.swift
> +    }
p2;
`setNavigation`이라는 이름이 조금 불명확한 것 같습니다.
Navigation의 title 내용과 크기를 조절하는 부분인 것 같은데 `setNavigationTitle`이라는 이름이 되면 어떨까 조심스럽게 제안해봅니다.

2022-08-12 13:36 UTC, taek0622 commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +    private let buttonBackground: UIView = {
p3;
해당 부분 이름이 `buttonBackground`인데 버튼의 배경색뿐만 아니라, 버튼의 기본 틀, 모양을 정의해주는 뷰에 더 가까운 것 같습니다.
혹시 `buttonShape`라는 이름은 어떨지 의견 제시해봅니다.

2022-08-12 13:46 UTC, GODNOEL commented on IntoHistory/MainView/MainViewController.swift
> +    private func setbuttonGesture() {
넵 반영했습니다.
09a39f8dd681485dc1c36b6c82e9a7984d4a3e5c

2022-08-12 13:46 UTC, GODNOEL commented on IntoHistory/MainView/MainViewController.swift
> +    }
넵 반영했습니다.
09a39f8dd681485dc1c36b6c82e9a7984d4a3e5c

2022-08-12 13:47 UTC, GODNOEL commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +    private let buttonBackground: UIView = {
넵 반영했습니다.
09a39f8dd681485dc1c36b6c82e9a7984d4a3e5c

2022-08-12 13:50 UTC, taek0622 approved these changes
수정 확인했습니다.
감사합니다~

2022-08-12 15:13 UTC, deslog reviewed
p1부분만 수정해주시면 될 것 같습니다! 고생많으셨습니다 ㅠㅠ 정말 디자인해두신거와 똑깥이!! 잘 만드셨네요,,, 일러스트그림부터 개발까지 정말 고생하셨습니다🥳👍✨

2022-08-12 15:13 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +    private func render() {
p5;

저희 viewcontroller를 구성하는 방식에 대해서도 통일하는게 필요할것 같네요. 아래서 이야기한것처럼 이것도 내일 스크럼에서 이야기해봐야할것 같습니다.

그리고 또 질문이하나있는데요,,,
configureUI와 render의 차이는 무엇인가요??

2022-08-12 15:13 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +    }
(질문) 

오, UIButton을 이용하지 않고 UIView에다가 제스쳐를 넣어 버튼으로 만드는 방식이네요! 한수 배워갑니다아아 👍
혹시 UIButton말고 이렇게 UIView로 구현한 이유는 안에 커스텀을 쉽게 하기 위해서였나요?!

2022-08-12 15:13 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +    lazy var flagAreaImage: UIImageView = {
p1;

접근제어자 추가 부탁드립니다! 
```suggestion
    private lazy var flagAreaImage: UIImageView = {
```

2022-08-12 15:13 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +    lazy var blackboardImage: UIImageView = {
p1;

접근제어자 추가 부탁드려요오오오 이 아래부터는 리뷰에선 달지 않겠습니다! 수정해주시면 감사할것같아욥🥳
```suggestion
    private lazy var blackboardImage: UIImageView = {
```

2022-08-12 15:13 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +        setButtonGesture()
p5;

setbuttonGesture는 UI가 아니기때문에 configureUI에 넣어주지 않으신거죠..?
전 render와 configureUI가 너무너무 헷갈리네용 ㅠㅠ

2022-08-12 15:13 UTC, deslog commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +    lazy var labelStack: UIStackView = {
p1;

현재 여기 labelStack도 MainViewButton 내부에서만 사용되고 있기 때문에 접근제어자가 필요해보입니다아 🤔
```suggestion
    private lazy var labelStack: UIStackView = {
```

2022-08-12 15:20 UTC, deslog commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +    }()
오오오 맞아요 이것도 정해봅시다. 저는 미뉴가 작성해주신방식대로 많이 썼었어요! 내일 VC전부를 통일시켜보아요오오

2022-08-12 16:02 UTC, taek0622 commented on IntoHistory/MainView/MainViewController.swift
> +    private func render() {
`render`가 여기에서는 `configureUI`와 같은 의미로 사용된 것 같습니다.

2022-08-12 16:17 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +    }
해당 답변은 위에 미뉴 댓글에서 확인 하였습니다 (머쓱..)

2022-08-12 23:55 UTC, GODNOEL commented on IntoHistory/MainView/MainViewController.swift
> +    private func render() {
configureUI는 View를 구성하는 기본항목들(네비게이션이나 백그라운드 등) 
render는 각 요소들을 추가하고 위치를 배치하는 레이아웃개념으로 사용했습니다!

2022-08-12 23:56 UTC, GODNOEL commented on IntoHistory/MainView/MainViewController.swift
> +    lazy var flagAreaImage: UIImageView = {
넵! 수정하도록 하겠습니다.
혹시 접근제어자를 사용하면 좋은 점 알 수 있을까요?

2022-08-12 23:57 UTC, GODNOEL commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +    lazy var labelStack: UIStackView = {
넵!

2022-08-13 00:34 UTC, deslog requested changes

2022-08-13 00:34 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +        buttonAreaBackground.anchor(top: blackboardImage.bottomAnchor, left: contentView.leftAnchor, bottom: view.bottomAnchor, right: contentView.rightAnchor, paddingTop: 30, paddingLeft: 0, padding
```suggestion
        buttonAreaBackground.anchor(
            top: blackboardImage.bottomAnchor, 
            left: contentView.leftAnchor, 
            bottom: view.bottomAnchor, 
            right: contentView.rightAnchor, 
            paddingTop: 30, 
            paddingLeft: 0, 
            paddingBottom: 0, 
            paddingRight: 0
        )
```

2022-08-13 00:34 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +        buttonAreaBackground.anchor(top: blackboardImage.bottomAnchor, left: contentView.leftAnchor, bottom: view.bottomAnchor, right: contentView.rightAnchor, paddingTop: 30, paddingLeft: 0, padding
이런식! 히히 (0813 데일리 스크럼)

2022-08-13 01:11 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +        setButtonGesture()
[0813 스크럼 결과 ViewController 작성방법](https://github.com/JamongSoda/IntoHistory/wiki/ViewController-Convention) 여기서 논의했으므로 답변주시지 않으셔도 됩니당 !

2022-08-13 01:12 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +    private func render() {
[0813 스크럼 결과 ViewController 작성방법](https://github.com/JamongSoda/IntoHistory/wiki/ViewController-Convention)

2022-08-13 01:17 UTC, deslog commented on IntoHistory/MainView/MainViewController.swift
> +    lazy var flagAreaImage: UIImageView = {
접근제어자는 모듈간의 접근을 제한할 수 있는 기능입니다. 현재 저희 앱처럼 간단한 동작으로 이루어져있는 앱일경우에는 문제되지 않을 수 있지만, 앱의 규모가 커질 때에는 불필요한 접근이 허용되는 상황이 발생하여 의도와는 다른 결과를 초래할 수 있습니다.

그래서 외부에서 호출될 가능성이 없고, 내부에서만 사용될 변수들에 대해서는 private를 무조건 써주는게 안정성 측면에서 훨씬 유리합니👍

2022-08-13 06:04 UTC, GODNOEL commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +        render()
금일 오전 스크럼에서 정해진 이름인 layout으로 수정했습니다.
17b65ba76c2de87fe9b7327b86c8bc5033cf8a08

2022-08-13 06:04 UTC, GODNOEL commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +        ])
수정했습니다.
17b65ba76c2de87fe9b7327b86c8bc5033cf8a08

2022-08-13 06:05 UTC, GODNOEL commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +        labelStack.anchor(left: buttonBackground.leftAnchor, paddingLeft: 25)
오전 스트럼에서 정해진 내용 반영했습니다.
17b65ba76c2de87fe9b7327b86c8bc5033cf8a08

2022-08-13 06:05 UTC, GODNOEL commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +    }()
오전 스트럼에서 정해진 내용 반영했습니다.
17b65ba76c2de87fe9b7327b86c8bc5033cf8a08

2022-08-13 06:06 UTC, GODNOEL commented on IntoHistory/MainView/MainViewController.swift
> +    lazy var flagAreaImage: UIImageView = {
넵 답변 감사합니다! 반영했습니다!
17b65ba76c2de87fe9b7327b86c8bc5033cf8a08

2022-08-13 06:06 UTC, GODNOEL commented on IntoHistory/MainView/MainViewController.swift
> +    lazy var blackboardImage: UIImageView = {
반영했습니다.
17b65ba76c2de87fe9b7327b86c8bc5033cf8a08

2022-08-13 06:06 UTC, GODNOEL commented on IntoHistory/MainView/support Views/MainViewButton.swift
> +    lazy var labelStack: UIStackView = {
반영했습니다.
17b65ba76c2de87fe9b7327b86c8bc5033cf8a08

2022-08-13 06:06 UTC, GODNOEL commented on IntoHistory/MainView/MainViewController.swift
> +        buttonAreaBackground.anchor(top: blackboardImage.bottomAnchor, left: contentView.leftAnchor, bottom: view.bottomAnchor, right: contentView.rightAnchor, paddingTop: 30, paddingLeft: 0, padding
반영했습니다.
17b65ba76c2de87fe9b7327b86c8bc5033cf8a08

2022-08-13 08:12 UTC, taek0622 approved these changes

2022-08-13 12:22 UTC, deslog approved these changes
리뷰 반영 확인 완료했습니다 ✨👍

2022-08-13 15:12 UTC, JUNY0110 reviewed
고생하셨습니다~

2022-08-13 15:13 UTC, taek0622 commented on IntoHistory/SceneDelegate.swift
> +        let nav = UINavigationController(rootViewController: MainViewController())
동감합니다. 해당 부분 약어는 `nav`보다는 `navi`가 더 잘 어울릴 것 같습니다.

2022-08-14 01:30 UTC, GODNOEL commented on IntoHistory/SceneDelegate.swift
> +        let nav = UINavigationController(rootViewController: MainViewController())
반영했습니다.
9bf2dfa7d615e29149387d52955c776a5d8a05e1

2022-08-14 02:31 UTC, merged