Feat/ar/38 ar UI
JamongSoda/IntoHistory pull request #55
Opened 2022-08-12 14:45 UTC by deslog

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- ARView를 생성했습니다.

## Key Changes 🔥 (주요 구현/변경 사항)
- TempButtonViewController : 임시로 화면 전환을 넣기 위한 뷰컨트롤러입니다. 전혀 신경쓰지 않아도 되고, 추후 mainview랑 연결 후 삭제할 예정입니다.
- ARView : 스토리보드로 Scene을 추가해주었습니다. (코드베이스로도 가능할텐데, 이해가 어려워 일단 스토리보드로 구현)
- ARViewController : ARView 스토리보드와 연결된 뷰 컨트롤러

## ToDo 📆 (남은 작업)
- [ ] 마지막에 객체를 클릭하면 화면이 전환되도록 해야합니다.
- [ ] AR창은 모달이 아니라 네비게이션으로 전환되어야할 것같습니다.
- [ ] 에디가 만든 화면 마지막루트에 AR연결
- [ ] 데이터 연결해야합니다.

## ScreenShot 📷 (참고 사진)
|AR화면 동작 gif|
|---|
|![AR](https://user-images.githubusercontent.com/96969693/184379367-01dd0056-9656-42a5-aaca-6c79ed74b7ee.gif)|

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 메인이 머지되면, 화면 연결을 하겠습니다.
- TempButtonViewController는 삭제예정입니다.
- 아직 AR에서 공이 하얀색으로 뜨는데, 추후 이미지 추가 예정입니다!
- 마지막에 공을 클릭하면 dismiss되어 modal이 내려가는 상황입니다. 현재 AR을 모달로 띄운상태인데, 이렇게 되게 되면 ```맨 마지막 루트를 방문했을때 AR로 가는 버튼 클릭 -> 모달로 AR등장 -> 객체 클릭시 화면 전환``` 이렇게 되는데, 보통 모달에서 화면전환이 이루어지기도 하나요??? 

## Reference 🔗
https://www.applaudostudios.com/blog/posts/augmented-reality-planetarium-using-arkit

## Close Issues 🔒 (닫을 Issue)
Close #38

2022-08-12 14:47 UTC, taek0622 commented
현재 target branch가 develop으로 설정 되어있습니다.
다른 브랜치로 변경 부탁드립니다.

2022-08-12 14:53 UTC, deslog commented
> 현재 target branch가 develop으로 설정 되어있습니다. 다른 브랜치로 변경 부탁드립니다.

아 죄송함니다 수정했습니다!

2022-08-12 14:57 UTC, taek0622 requested changes
고생하셨습니다~
일부 수정이 필요한 부분이 있는 것 같습니다.
확인 부탁드려요~

2022-08-12 14:57 UTC, taek0622 commented on IntoHistory/Screens/ARView/ARViewController.swift
> +        let hitResults : [SCNHitTestResult] = sceneView.hitTest(touchLocation, options: [:])
p2;
여기 인덴테이션이 잘못된 것 같습니다.
`let hitResults: [SCNHitTestResult]`처럼 콜론 왼쪽 인덴트 삭제 부탁드려요~

2022-08-12 14:57 UTC, taek0622 commented on IntoHistory/Screens/ARView/ARViewController.swift
> +            let material : SCNMaterial? = node.geometry?.material(named : "Color")
p2;
여기도 인덴테이션이 잘못된 것 같아요.
맨 마지막에 `named: "Color"`처럼 콜론 왼쪽 인덴트 삭제 부탁드립니다~

2022-08-12 14:57 UTC, taek0622 commented on IntoHistory/Screens/ARView/SupportViews/TempButtonViewController.swift
> +        layout()
p4;
layout이라는 이름도 좋지만 조금 더 직관적인 다른 이름을 사용해보는 건 어떨까요?
더 좋은 이름에 대해서 내일 스크럼 이후에 같이 이야기해보면 좋을 것 같아요~

2022-08-12 15:00 UTC, taek0622 commented
일반적으로 모달에서는 화면 전환이 이루어지지 않는 것으로 알고 있습니다.
해당 부분을 일반적인 모달이 아닌 FullScreenCover 같은 것으로 바꾸면 어떨까요?
아, 다만 FullScreenCover의 경우 SwiftUI에서 사용하는 이름이라 UIKit에서는 어떤 이름으로 사용하는지 잘 모르겠네요..

2022-08-12 15:16 UTC, deslog commented on IntoHistory/Screens/ARView/ARViewController.swift
> +        let hitResults : [SCNHitTestResult] = sceneView.hitTest(touchLocation, options: [:])
대박사건, 이런걸 확인도안하고 바로 날리다니,, 죄송함다 바로 수정했습니다 ㅠㅠ [f07a95b](https://github.com/JamongSoda/IntoHistory/pull/55/commits/f07a95bea3afd7c7bacea048f09a63e45dc16133)

2022-08-12 15:17 UTC, deslog commented on IntoHistory/Screens/ARView/ARViewController.swift
> +            let material : SCNMaterial? = node.geometry?.material(named : "Color")
ㅠㅠ수정완료 참으로 불편하군요 제가봐도... [f07a95b](https://github.com/JamongSoda/IntoHistory/pull/55/commits/f07a95bea3afd7c7bacea048f09a63e45dc16133)

2022-08-12 15:17 UTC, deslog commented on IntoHistory/Screens/ARView/SupportViews/TempButtonViewController.swift
> +        layout()
네!! 좋아요 ㅠㅠ 저도 render, layout등 다 충분히 와닿지가 않아요 ㅎㅎㅎ,,, 내일 이야기나눠보고, viewcontroller 형태?? 도 맞추면 좋을것같슴니다~

2022-08-12 15:18 UTC, deslog commented
> llScreenCover 같은 것으로 바꾸면 어떨

아 모달에서 전환은 안되는군요!! full screen 저도 알아볼게요!

아니면, AR화면은 네비게이션으로 넘어가고, AR에서 객체를 클릭했을때 모달로 띄우는방법? 도 있을것같아요. 이것도 오늘 더 찾아보고 내일 스크럼때 주제를 던져보겠습니다!

2022-08-12 16:13 UTC, taek0622 requested changes
수정 확인했습니다.
다만, 추가적으로 인덴테이션을 한번 쭉 살펴보는 것이 좋을 것 같아요~

2022-08-12 16:13 UTC, taek0622 commented on IntoHistory/Screens/ARView/ARViewController.swift
> +    @objc func tapped(recognizer : UITapGestureRecognizer){
p2;
여기도 인덴테이션 수정이 필요해 보이네요.
`recognizer` 뒤에 인덴트 제거, `UITapGestureRecognizer)` 뒤에 인덴트 추가가 필요해보입니다.

2022-08-12 16:15 UTC, deslog commented on IntoHistory/Screens/ARView/ARViewController.swift
> +    @objc func tapped(recognizer : UITapGestureRecognizer){
죄송합니다 [9bc5f01](https://github.com/JamongSoda/IntoHistory/pull/55/commits/9bc5f010ca4f72d964a837ad6a681bf432ad2a01)

2022-08-12 17:02 UTC, JUNY0110 approved these changes
AR고생하셨습니다~

2022-08-12 17:02 UTC, JUNY0110 commented on IntoHistory/Screens/ARView/ARViewController.swift
> +        let hitResults: [SCNHitTestResult] = sceneView.hitTest(touchLocation, options: [:])
질문)
`sceneView.hitTest(touchLocation, options: [:])`의 options가 빈 딕셔너리가 있는데, options의 쓰임이 궁금합니다.

2022-08-12 19:37 UTC, deslog commented on IntoHistory/Screens/ARView/ARViewController.swift
> +        let hitResults: [SCNHitTestResult] = sceneView.hitTest(touchLocation, options: [:])
[```scenekit.hittest``` 공식문서](https://developer.apple.com/documentation/scenekit/scnscenerenderer/1522929-hittest)

sceneView.hitTest의 기본 형태는 아래와 같습니다. 

<img width="449" alt="image" src="https://user-images.githubusercontent.com/96969693/184429311-8db3f57b-4c7d-40c0-90ab-c36a3f211eeb.png">

```.hittest``` 는 사용자의 터치가 발생했을때 그 포인트를 알아내서 적절한 결과값을 내어줍니다 (touchLocation 파라미터가 이 포인트를 알아내는 역할을 하고 터치가 발생했을때 CGPoint 형태로 좌표값을 받아옵니다). 그리고 두번재 파라미터인 options는 hittest의 결과값을 찾을 때, 어떠한 옵션을 두어 결과값을 찾을지에 대한 '사전'과 같은 역할을 합니다. options에는 

<img width="744" alt="image" src="https://user-images.githubusercontent.com/96969693/184430356-ac34168f-a51c-4089-b80f-70ce03695320.png">

이것외에 더 많지만, 이러한 옵션이 들어갈 수 있고, 이런 옵션이 들어갈 경우 '터치이벤트가 발생했을때, 자식노드를 제외하고 결과값을 찾겠다' 이런식으로 조건을 넣어 결과값을 받을 수 있다 라고 생각하시면 좋을 것 같습니다!

저희는 객체가 클릭되었을때, 별도의 옵션 없이 지정된 뷰를 띄워주면 되어 ```options```칸을 비워둔채로,형식에 맞게 써둔것입니다. 빈 딕셔너리를 지우고 ```nil```로 해도 아마 별 차이 없이 똑같이 동작할 것으로 예상됩니다.

2022-08-12 19:44 UTC, deslog commented on IntoHistory/Screens/ARView/SupportViews/TempButtonViewController.swift
> +            print("button tapped")
네 수정했습니다! 7e65b2b

2022-08-12 19:44 UTC, deslog commented on IntoHistory/Screens/ARView/ARViewController.swift
> +            print("AR box가 tap 되었습니다아")
수정완료! 7e65b2b

2022-08-13 06:08 UTC, GODNOEL approved these changes
오오 AR 너무 멋지네요! 
자료도 많지않다고 들었는데 구현하시느라 고생많으셨습니다😎👍

2022-08-13 08:14 UTC, taek0622 approved these changes

2022-08-13 11:06 UTC, merged