[Design] 호국 영웅 상세정보 보기 팝업 레이아웃 추가 (Merge herolistview to develop)
JamongSoda/IntoHistory pull request #73
Opened 2022-08-14 13:23 UTC by taek0622

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 호국 영웅 목록에서 호국 영웅을 클릭했을 때 나오는 호국 영웅 상세보기 팝업을 추가하기 위함

## Key Changes 🔥 (주요 구현/변경 사항)
- 호국 영웅 상세보기 팝업 레이아웃 추가
- 불필요한 주석 삭제
- ViewController의 구간을 구분하기 위한 MARK 주석 추가
- 컨벤션에 맞게 constriant 코드 위치 변경

## ToDo 📆 (남은 작업)
- [ ] 호국 영웅 상세정보 보기 기능 (데이터 연동, 팝업 띄우기 등)

## ScreenShot 📷 (참고 사진)
![스크린샷 2022-08-14 13 10 56](https://user-images.githubusercontent.com/81027256/184522131-ed4f5689-9430-48dd-8608-de403cd8af5f.png)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 간단한 레이아웃 추가이지만, 꼼꼼한 리뷰 부탁드립니다.
- `herolistview` branch에서 `develop` branch 머지입니다. 한 번 더 꼼꼼한 확인 부탁드려요~

## Reference 🔗
- 없음

## Close Issues 🔒 (닫을 Issue)
Close #64

2022-08-14 14:27 UTC, deslog approved these changes
popup띄우는게 엄청 복잡할 줄 알았는데 uiveiw를 이용해서 띄울수가 있네요! 특별한 수정사항은 없고 의견들만 조심스럽게 적어봤습니다.
LGTM~👍

가족여행중이라 작업이 힘들어서 많이 참여 못한점 죄송합니다 ㅠㅠ

2022-08-14 14:27 UTC, deslog commented on IntoHistory/HeroDetailViewController.swift
> +        popupShape.addSubview(heroDescription)
p5;

이렇게 foreach와 클로저 이용해서도 addsubview가 가능합니다! 이건 그냥 ... 제가 지난번에 사용했던 방식이라 공유드립니당.

```suggestion
        [closeButton, heroImgae, heroName, heroDescription].forEach { popupShape.addSubview($0) }
```

2022-08-14 14:27 UTC, deslog commented on IntoHistory/HeroDetailViewController.swift
> +#endif
p5;

프리뷰를 외부파일 ```UIViewController+Extension```으로 빼면 어떨까요?? 유용할것 같아서요~!

2022-08-14 14:27 UTC, deslog commented on IntoHistory/HeroDetailViewController.swift
> +        view.backgroundColor = UIColor(red: 0, green: 0, blue: 0, a: 0.5)
p4;

```Color+Extension```에 추가해서 사용하는게 어떨지 조심스럽게 의견을 제안해 봅니다ㅎㅎ

2022-08-15 01:50 UTC, taek0622 commented on IntoHistory/HeroDetailViewController.swift
> +        popupShape.addSubview(heroDescription)
오, 이런 방법이 있군요. 좋은 정보 감사합니다~
해당 부분은 5c93193 에서 반영했습니다. 감사합니다~

2022-08-15 01:55 UTC, taek0622 commented on IntoHistory/HeroDetailViewController.swift
> +        view.backgroundColor = UIColor(red: 0, green: 0, blue: 0, a: 0.5)
오, 좋습니다. popup의 dim에서 한 번만 사용될 것 같은 색상이라 하드코딩으로 박아놨었는데, color extension으로 관리하면 더 좋을 것 같습니다.
해당 부분은 f84a5c5 와 f927090 으로 Color Extension에 추가되고, 해당 extension에서 색을 가져와서 사용하는 것으로 변경하도록 반영하였습니다. 감사합니다~

2022-08-15 02:00 UTC, taek0622 commented on IntoHistory/HeroDetailViewController.swift
> +#endif
Preview용 코드라서 안올리려고 했는데, 실수로 같이 올라간 것 같습니다.
다만, 필요하신 분들이 더 쉽게 사용할 수 있도록 해당 부분은 Extension으로 별도로 뺐습니다.
Preview 사용이 필요하신 분들은 HeroDetailViewController.swift 파일의 최하단에 있는 코드를 적절하게 복사하여 수정해서 사용하시면 될 것 같습니다. 감사합니다~

9b8e7ea

2022-08-15 11:09 UTC, JUNY0110 requested changes
고생하셨습니다. 근데 프로젝트가 열리지 않네요. 브랜치를 다시 확인해주시면 감사하겠습니다.

2022-08-15 11:09 UTC, JUNY0110 commented on IntoHistory/HeroListViewController.swift
>  extension HeroListViewController: UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
p1.
extension이 중복으로 잡혀있습니다. rebase이후 체크되지 않은 부분같습니다.
실행이 되지 않는 이유 중 하나 입니다.

2022-08-15 11:09 UTC, JUNY0110 commented on IntoHistory/HeroDetailViewController.swift
> +    }
p4. 
이 부분에서 작업할 내용일지 잘 모르겠으나, popup이 나타났을 때 배경이 모두 회색인 것이 자연스러울 것 같습니다. 상, 하단 safearea까지 배경을 넣으면 좋을 것 같네요!

2022-08-15 12:39 UTC, taek0622 commented on IntoHistory/HeroListViewController.swift
>  extension HeroListViewController: UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
해당 부분은 다른 분의 브랜치에서 이미 수정되어서 중복 및 컨플릭트를 피하기 위해 일부러 남겨두었습니다.

2022-08-15 12:45 UTC, taek0622 commented on IntoHistory/HeroDetailViewController.swift
> +    }
프리뷰만 보시고 상 하단 safeArea가 채워지지 않았다고 생각하신 것 같습니다만, 실제 시뮬레이터에서는 꽉 채워서 나온답니다~
해당 부분 비교 스크린샷을 첨부합니다.
|프리뷰|시뮬레이터|
|:-:|:-:|
|<img width="300" alt="스크린샷 2022-08-15 21 44 23" src="https://user-images.githubusercontent.com/81027256/184637247-b0db702a-7f4a-4ae8-9f87-d82169e22bfc.png">|<img width="300" alt="스크린샷 2022-08-15 21 44 33" src="https://user-images.githubusercontent.com/81027256/184637275-1b31f861-d0f1-4f21-a455-42614fd195b0.png">|

2022-08-15 14:03 UTC, JUNY0110 approved these changes

2022-08-15 14:40 UTC, merged