[!Resource] json 파일 수정 (Merge json to develop 재수정)
JamongSoda/IntoHistory pull request #96
Opened 2022-08-15 16:00 UTC by taek0622

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 필요한 데이터의 구조 변경 및 인물 이슈

## Key Changes 🔥 (주요 구현/변경 사항)
- 더 이상 사용되지 않을 person_json.json 파일 삭제
- course_json.json의 구조 수정
  - course_pin에 address 칼럼 추가
  - related_person에 image 칼럼 추가
- course_json.json의 인물 변경

## ToDo 📆 (남은 작업)
- 없음

## ScreenShot 📷 (참고 사진)
- 없음

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- json 데이터가 수정되었습니다. 확인 부탁드립니다.
- 일부 파일도 삭제 되었으니 꼼꼼한 리뷰 부탁드립니다.
- `json` branch에서 `develop` branch로의 Merge 입니다. 다시 한번 꼼꼼한 리뷰 부탁드려요~
- 이전 브랜치에서 심각한 컨플릭트 문제로 새 PR로 다시 돌아왔습니다. 다시 한번 리뷰 부탁드립니다.

## Reference 🔗
- 없음

## Close Issues 🔒 (닫을 Issue)
Close #86

2022-08-15 18:11 UTC, JUNY0110 requested changes
수정이 안 된 부분을 다시 수정해주시기 바랍니다.

2022-08-15 18:11 UTC, JUNY0110 commented on IntoHistory/Data/course_json.json
> +                "pin_address": "서울특별시 종로구 194-27, 태화빌딩, 802호",
p2
'서울특별시 종로구 194-27'로 수정 바랍니다.

2022-08-15 18:11 UTC, JUNY0110 commented on IntoHistory/Data/course_json.json
> +        "transportation": "드라이브",
p2. 
'차량'으로 수정바랍니다.

2022-08-15 18:11 UTC, JUNY0110 commented on IntoHistory/Data/course_json.json
> +        "region": "충남 예산·홍성",
p2.
'홍성'으로 수정 바랍니다.

2022-08-15 18:11 UTC, JUNY0110 commented on IntoHistory/Data/course_json.json
> +        "region": "경북 칠곡(왜관)",
p2.
'칠곡'으로 수정바랍니다.

2022-08-15 18:11 UTC, JUNY0110 commented on IntoHistory/Data/course_json.json
> +        "region": "강원 화천",
p2. 
'화천'으로 수정바랍니다.

2022-08-15 18:11 UTC, JUNY0110 commented on IntoHistory/Data/course_json.json
> +        "region": "강원 양구",
p2.
'양구'로 수정 바랍니다.

2022-08-15 18:11 UTC, JUNY0110 commented on IntoHistory/Data/course_json.json
> +        "region": "강원 고성",
p2.
'고성'으로 수정바랍니다.

2022-08-15 18:13 UTC, taek0622 commented on IntoHistory/Data/course_json.json
> +        "transportation": "드라이브",
확인했습니다. ac0e4bb 에서 반영되었습니다~

2022-08-15 19:41 UTC, taek0622 commented on IntoHistory/Data/course_json.json
> +                "pin_address": "서울특별시 종로구 194-27, 태화빌딩, 802호",
확인했습니다. 해당 부분은 5c38246 에서 반영 되었습니다~

2022-08-15 19:41 UTC, taek0622 commented on IntoHistory/Data/course_json.json
> +        "region": "충남 예산·홍성",
확인했습니다. 해당 부분은 5c38246 에서 반영 되었습니다~

2022-08-15 19:41 UTC, taek0622 commented on IntoHistory/Data/course_json.json
> +        "region": "경북 칠곡(왜관)",
확인했습니다. 해당 부분은 5c38246 에서 반영 되었습니다~

2022-08-15 19:41 UTC, taek0622 commented on IntoHistory/Data/course_json.json
> +        "region": "강원 화천",
확인했습니다. 해당 부분은 5c38246 에서 반영 되었습니다~

2022-08-15 19:42 UTC, taek0622 commented on IntoHistory/Data/course_json.json
> +        "region": "강원 양구",
확인했습니다. 해당 부분은 5c38246 에서 반영 되었습니다~

2022-08-15 19:42 UTC, taek0622 commented on IntoHistory/Data/course_json.json
> +        "region": "강원 고성",
확인했습니다. 해당 부분은 5c38246 에서 반영 되었습니다~

2022-08-16 01:08 UTC, deslog approved these changes
LGTM

2022-08-16 01:42 UTC, JUNY0110 approved these changes
굿

2022-08-16 01:42 UTC, merged